### PR TITLE
Alias function (errors)

### PR DESCRIPTION
**Pull request by 2sumithrasuresh**
Alias function works but exits out of psh loop when called

### CODE REVIEW

**Comment by tejas-techstack** [comment]
image

**Comment by g-anupam** [comment]
This branch now has a  merge conflict due to another PR being merged. @tejas-techstack is the bug fixed?

**Comment by tejas-techstack** [comment]
uh ill try fixing the conflicts for now but i dont think the bug has been fixed yet, atleast i havent gotten an update about the bug fix

**Comment by polarhive** [comment]
Mentors gonna work on this tomo, consider this PR closed apart from merge conflicts.

I'll `git checkout a810a50c0e692d839cea06ad2ee553fbc9733232` this works when you comment out that return -1 at line 705.

**Review by polarhive — APPROVED** [review]
Merging this for now, tackle #80 in w5

**Pull request merged**
