### PR TITLE
EXPORT Function

### PR DESCRIPTION
**Pull request by 2sumithrasuresh**
- Created EXPORT function
    - Works for export __ , export -p, export -n

- Modified READ function to accept variable assignment
- Added 2 helper functions to help with sorting

- Code for function declaration in READ function and EXPORT  function is commented

### CODE REVIEW

**Comment by tejas-techstack** [comment]
Screenshot from 2024-07-11 15-50-51

**Comment by tejas-techstack** [comment]
hey okay so i tested the code
-n and -p work perfectly so thats amazing
the main export function also works amazing just one thing add a functionality to use "" also
so like export TEST_VAR="testing name" should save the entire phrase and not end at the first space
but everything else is working perfectly
if u have time and arent working on anything try to do this otherwise dont bother much about it

**Review by tejas-techstack — APPROVED** [review]
working perfectly, need to add quotes functionality but can be done later in another pr

**Comment by 2sumithrasuresh** [comment]
> hey okay so i tested the code -n and -p work perfectly so thats amazing the main export function also works amazing just one thing add a functionality to use "" also so like export TEST_VAR="testing name" should save the entire phrase and not end at the first space but everything else is working perfectly if u have time and arent working on anything try to do this otherwise dont bother much about it

I think updating the tokenizer would solve the issue of the value ending at the first space. I'm still trying to figure out how I can implement functions so I can update the tokenizer in one go. Any inputs on that would be appreciated.

Or I can just update the tokenizer to work for the quotes.

**Pull request merged**
